### PR TITLE
fix(Geosuggest): clear suggestion on empty input

### LINKED ISSUE #201: Clearing the suggestion
How do you handle the scenario where after selecting a suggest the user erases their entry (partially or totally)? Currently it keeps the last suggest as value, so the form will erroneously save the last selected suggestion even though the user has chosen to erase their input.

### PR DESCRIPTION
**Pull request by manjumuthaiya**
### Description
This fixes #201 
When a place is selected and then cleared by erasing the input field, it should also clear out the previous selection from the model.
My fix is to call `onSuggestSelect` with `undefined` so the previously selected place is cleared out
Also added the selected place to the example UI for easy verification

### Checklist

- [ ] All tests passing
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary
- [ ] Commits and PR follow conventions

### CODE REVIEW

**Comment by manjumuthaiya** [comment]
@ro-ka Could you please review this and let me know if it looks ok? thanks :)

File: example/src/app.js [hunk 1]
```diff
@@ -66,6 +76,9 @@ class App extends React.Component {
           onSuggestNoResults={this.onSuggestNoResults}
           location={new google.maps.LatLng(53.558572, 9.9278215)}
           radius="20" />
+        <div>
+          {this.state.selectedSuggest && this.state.selectedSuggest.label}
+        </div>
```
Comment (ro-ka) [inline example/src/app.js]: Please leave this out of the example. It helps to demonstrate the issue but is not for showcasing the component.

**Comment by manjumuthaiya** [comment]
@ro-ka : Done! 

And congrats!! :)

**Comment by ro-ka** [comment]
Nice, thanks!  😃
